"""Write refined grids out as C++ headers.

A note on why the tables are emitted as decimal strings rather than numeric
literals. The existing data headers say

    template <typename T>
    struct lebedev_laikov_50 {
      static constexpr std::array<cartesian_pt_t<T>, 50> points = {
          0.3015113445777636, ...

A floating literal with no suffix has type ``double`` whatever ``T`` is, so the
value is rounded to 53 bits before it is ever converted. Writing more digits
changes nothing: the table cannot carry more than double precision, and a
``long double`` or ``__float128`` instantiation silently gets a double-rounded
grid. Suffixes do not fix it either, since one table would have to serve every
``T``.

Emitting the decimal digits as strings and converting them at grid construction
sidesteps this entirely, works for MPFR and Boost.Multiprecision as well as the
built-in types, and costs one parse per grid.
"""
from mpmath import mp

HEADER = """#pragma once

// Generated by tools/angular_grids -- do not edit.
//
// {family} quadrature on S^2, {npts} points, algebraic order {order}.
// Refined from the tabulated double-precision rule by Gauss-Newton on the
// exactness conditions; see tools/angular_grids/README.md.
//
// Digits carried: {digits}. Verified worst relative error over all even
// monomials up to degree {order}: {error}.

#include <integratorxx/types.hpp>
#include <integratorxx/util/grid_scalar.hpp>

#include <array>
#include <cstddef>

namespace IntegratorXX {{
namespace {ns} {{

template <typename T>
struct {struct_name} {{
  static constexpr size_t npts = {npts};
  static constexpr int algebraic_order = {order};

  /// Decimal digits of the quadrature points, x0 y0 z0 x1 y1 z1 ...
  static constexpr const char* const point_digits[3 * {npts}] = {{
{points}
  }};

  /// Decimal digits of the quadrature weights, normalised to sum to 4*pi.
  static constexpr const char* const weight_digits[{npts}] = {{
{weights}
  }};

  /// Materialise the grid at the working precision of T.
  ///
  /// Templated on the containers so it can fill the library's
  /// std::vector<cartesian_pt_t<T>> / std::vector<T> directly, in the same
  /// role detail::copy_grid played for the literal tables.
  template <typename PointContainer, typename WeightContainer>
  static void load(PointContainer& p, WeightContainer& w) {{
    for(size_t i = 0; i < {npts}; ++i) {{
      for(size_t j = 0; j < 3; ++j)
        p[i][j] = detail::grid_scalar<T>::parse(point_digits[3 * i + j]);
      w[i] = detail::grid_scalar<T>::parse(weight_digits[i]);
    }}
  }}
}};

}}  // namespace {ns}
}}  // namespace IntegratorXX
"""

NAMESPACES = {"lebedev_laikov": "LebedevLaikovGrids", "delley": "DelleyGrids",
              "ahrens_beylkin": "AhrensBeylkinGrids", "womersley": "WomersleyGrids"}
TITLES = {"lebedev_laikov": "Lebedev-Laikov", "delley": "Delley",
          "ahrens_beylkin": "Ahrens-Beylkin", "womersley": "Womersley"}


def _fmt(values, digits, per_line):
    out, line = [], []
    for v in values:
        line.append('"%s"' % mp.nstr(v, digits, strip_zeros=False))
        if len(line) == per_line:
            out.append("      " + ", ".join(line) + ",")
            line = []
    if line:
        out.append("      " + ", ".join(line) + ",")
    return "\n".join(out).rstrip(",")


def emit(family, npts, order, points, weights, digits, error):
    flat = [c for p in points for c in p]
    return HEADER.format(
        family=TITLES.get(family, family), ns=NAMESPACES.get(family, family),
        struct_name=f"{family}_{npts}", npts=npts, order=order, digits=digits,
        error=mp.nstr(error, 4),
        points=_fmt(flat, digits, 3), weights=_fmt(weights, digits, 3))
